// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDVo06rTXOgUsC5jw6ch8p9_7NaELnKvg',
    appId: '1:516417498596:web:daaa46e66a6ff020506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
    authDomain: 'dek-belajar.firebaseapp.com',
    databaseURL:
        'https://dek-belajar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dek-belajar.appspot.com',
    measurementId: 'G-F05V5VMP67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwtR09Zwl7RFezdgNeLChwk8a2UlGIMg',
    appId: '1:516417498596:android:abedeaf82f6a40e5506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
    databaseURL:
        'https://dek-belajar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dek-belajar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDf_ipfvfA0FkTKd0L12hkGAd7mOODMI',
    appId: '1:516417498596:ios:10f52487e3e36bb8506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
    databaseURL:
        'https://dek-belajar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dek-belajar.appspot.com',
    iosClientId:
        '516417498596-5rsaqsv5f4cn9sjllvj0kjqmps8l1kk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectEdspert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFDf_ipfvfA0FkTKd0L12hkGAd7mOODMI',
    appId: '1:516417498596:ios:10f52487e3e36bb8506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
    databaseURL:
        'https://dek-belajar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dek-belajar.appspot.com',
    iosClientId:
        '516417498596-5rsaqsv5f4cn9sjllvj0kjqmps8l1kk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectEdspert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFDf_ipfvfA0FkTKd0L12hkGAd7mOODMI',
    appId: '1:516417498596:ios:10f52487e3e36bb8506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBFDf_ipfvfA0FkTKd0L12hkGAd7mOODMI',
    appId: '1:516417498596:ios:10f52487e3e36bb8506bf1',
    messagingSenderId: '516417498596',
    projectId: 'dek-belajar',
  );
}
